name: Check Lamassu Docs
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  doc-format-check:
    name: Lamassu Doc Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5.1.0
        with:
            python-version: '3.10'
      - name: Install PIP
        run: |
          python -m pip install --upgrade pip
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pip install -r .devcontainer/pip-ci-reqs.txt
      - name: Check format
        run: |
          mdformat --check --wrap 80  docs/*.md
