name: Publish Lamassu Docs
on:
  workflow_dispatch:

jobs:
  doc-publisher:
    name: Lamassu Doc Publiser
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - name: Install PIP
        run: |
          python -m pip install --upgrade pip
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pip install -r .devcontainer/pip-reqs.txt
      - name: Set git info
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
      - name: Get version
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Set latest alias for doc from main
        if: github.ref_name == 'main'
        run: |
          mike deploy ${{env.VERSION}} latest -u
          mike set-default ${{env.VERSION}}
      - name: Publish docs for version
        run: |
          mike deploy ${{env.VERSION}} -b gh-pages --push
