name: Publish Lamassu Docs
on:
  workflow_dispatch:

jobs:
  doc-publisher:
    name: Lamassu Doc Publiser
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - name: Install PIP
        run: |
          python -m pip install --upgrade pip
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r .devcontainer/pip-reqs.txt
      - name: Publish docs for version
        run: |
          VERSION=$(cat VERSION)
          mike deploy $VERSION -b gh-pages --push
